name: reviewdog check
# Run on pull_request too to run the workflow on Pull Rquests from forked
# repositories.
on: [push, pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Add $GOPATH/bin
        run: |
          echo ::add-path::$(go env GOPATH)/bin

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install linters
        run: '( cd linters && go get golang.org/x/lint/golint )'

      - name: Setup reviewdog
        run: |
          # mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          # echo ::add-path::$HOME/bin
          go install ./cmd/reviewdog

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          golint ./... | reviewdog -f=golint -name=golint-github-check -reporter=github-check -level=warning
